version: '3.8'

services:
  amio-api:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000" # container listens on 8000; mapped to host 8000
    networks:
      - amio-net

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - amio-api
    networks:
      - amio-net

networks:
  amio-net:
    driver: bridge
